services:

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=grid
    ports:
      - 5432:5432
    
    restart: always

  grid:
    image: ${DOCKER_REGISTRY-}grid
    container_name: grid
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    build:
      context: .
      dockerfile: GRID/Dockerfile
    ports:
      - 35510:8080
      - 35511:8081
    depends_on:
      - db