// <auto-generated />
using System;
using GRID.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GRID.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328000002_AddAdvancedFeatures")]
    partial class AddAdvancedFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GRID.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorId").HasColumnType("text");
                    b.Property<string>("ActorEmail").HasColumnType("text");
                    b.Property<string>("Action").IsRequired().HasColumnType("text");
                    b.Property<string>("EntityType").HasColumnType("text");
                    b.Property<string>("EntityId").HasColumnType("text");
                    b.Property<string>("Details").HasColumnType("text");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");
                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GRID.Models.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.Property<string>("UserEmail").IsRequired().HasColumnType("text");
                    b.Property<bool>("Succeeded").HasColumnType("boolean");
                    b.Property<string>("IpAddress").HasColumnType("text");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");
                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("GRID.Models.ServiceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Token").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<string>("Url").IsRequired().HasColumnType("text");
                    b.Property<string>("IconClass").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<bool>("RequiresAuth").HasColumnType("boolean");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<bool>("ShowInNav").HasColumnType("boolean");
                    b.Property<bool>("ShowOnHomePage").HasColumnType("boolean");
                    b.Property<int>("DisplayOrder").HasColumnType("integer");

                    b.HasKey("Id");
                    b.ToTable("ServiceLinks");
                });

            modelBuilder.Entity("GRID.Models.UserProfile", b =>
                {
                    b.Property<string>("UserId").HasColumnType("text");
                    b.Property<bool>("IsDeactivated").HasColumnType("boolean");
                    b.Property<DateTime?>("DeactivatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Theme").HasMaxLength(10).HasColumnType("character varying(10)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");
                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("GRID.Models.ContactRequest", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<bool>("IsResponded").HasColumnType("boolean");
                    b.Property<string>("Message").IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime?>("RespondedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Subject").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<DateTime>("SubmittedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("GRID.Models.Invite", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Code").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("CurrentUses").HasColumnType("integer");
                    b.Property<string>("Email").HasColumnType("text");
                    b.Property<DateTime?>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<bool>("IsSingleUse").HasColumnType("boolean");
                    b.Property<int?>("MaxUses").HasColumnType("integer");
                    b.Property<string>("Role").HasColumnType("text");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("bytea");
                    b.HasKey("Id");
                    b.ToTable("Invites", t => { t.HasCheckConstraint("CK_Invites_Uses", "\"MaxUses\" IS NULL OR \"CurrentUses\" <= \"MaxUses\""); });
                });

            modelBuilder.Entity("GRID.Models.InviteUsage", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<int>("InviteId").HasColumnType("integer");
                    b.Property<DateTime>("UsedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("UserId").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("InviteId");
                    b.ToTable("InviteUsages");
                });

            modelBuilder.Entity("GRID.Models.InviteUsage", b =>
                {
                    b.HasOne("GRID.Models.Invite", "Invite")
                        .WithMany("Usages")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Invite");
                });

            modelBuilder.Entity("GRID.Models.Invite", b =>
                {
                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
